# on:
#   push:
#     branches:
#     - main

#   schedule:
#     - cron: '0 * * * *'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2.3.3
#       - name: HubSpot Deploy To Template Marketplace
#         uses: HubSpot/hubspot-cms-deploy-action@v1.7
#         with:
#           src_dir: .
#           dest_dir: themes/testing-new-mod.module
#           portal_id: ${{ secrets.TEMPLATE_MARKETPLACE_AC_ID }}
#           personal_access_key: ${{ secrets.TEMPLATE_MARKETPLACE_PA_TOKEN }}